### ISSUE TITLE
Soul Reaver

### ISSUE THREAD

**Issue by Brullworfel** [ProgmanGame/i#1]
Привет! Я видел твой проект в YouTube, я занимался тем же самым и были некоторые идеи, что из этого можно сделать, но когда увидел твой проект, понял что у тебя видимо больше времени на это - могу ли я связаться с тобой чтобы поделиться своими мыслями и прогрессом? Напиши пожалуйста на _______

**Comment by ProgmanGame** [comment]
Привет, да конечно.

ср, 31 янв. 2024 г., 00:08 Brullworfel ***@***.***>:
